spring:
  main:
    banner-mode: off
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:restchooser
    #    url: jdbc:postgresql://localhost:5432/restchooser
    username: user
    password: password
  h2.console.enabled: true

  jackson:
    default-property-inclusion: non_empty
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none

logging:
  level:
    root: WARN
    ru.tuzov.restchooser: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.web: DEBUG

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8080